global:
  scrape_interval:     15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'federate'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="kubernetes-apiservers"}'
        - '{job="kubernetes-nodes"}'
        - '{job="kubernetes-nodes-cadvisor"}'
        - '{job="kubernetes-pods-slow"}'
        - '{job="kubernetes-service-endpoints"}'
        - '{job="kubernetes-service-endpoints-slow"}'
        - '{job="kubernetes-services"}'
        - '{job="prometheus"}'
        - '{job="prometheus-pushgateway"}'
        
    static_configs:
      - targets:
        - '35.192.199.30:30399'
