global:
  scrape_interval:     15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'federate'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="kubernetes-apiservers|kubernetes-nodes|kubernetes-nodes-cadvisor|kubernetes-pods|kubernetes-pods-slow|kubernetes-service-endpoints|kubernetes-service-endpoints-slow|prometheus-pushgateway"}'

    static_configs:
      - targets:
        - '35.192.199.30:30399'
